# Generated by Django 2.0.3 on 2020-09-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
