# Generated by Django 2.0.3 on 2020-10-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
